# Site settings
title: Another Blog
email: your_email@example.com
author: your_name
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: > # until "timezone:"
  One sentence introducing yourself.
#timezone: Asia/Chongqing
description: > # this means to ignore newlines until "baseurl:"
  One or more sentences introducing this blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables